// 200 additional common job titles for AI analysis generation
// Based on BLS top occupations, common search terms, and gap analysis

export interface JobCandidate {
  title: string
  slug: string
}

export const jobCandidates: JobCandidate[] = [
  // Retail & Sales
  { title: "Retail Salesperson", slug: "retail-salesperson" },
  { title: "Cashier", slug: "cashier" },
  { title: "Store Manager", slug: "store-manager" },
  { title: "Retail Store Associate", slug: "retail-store-associate" },
  { title: "Sales Manager", slug: "sales-manager" },
  { title: "Account Executive", slug: "account-executive" },
  { title: "Business Development Manager", slug: "business-development-manager" },
  { title: "Wholesale Buyer", slug: "wholesale-buyer" },
  { title: "Merchandise Planner", slug: "merchandise-planner" },
  { title: "Visual Merchandiser", slug: "visual-merchandiser" },

  // Food Service & Hospitality
  { title: "Fast Food Worker", slug: "fast-food-worker" },
  { title: "Waiter", slug: "waiter" },
  { title: "Waitress", slug: "waitress" },
  { title: "Host/Hostess", slug: "host-hostess" },
  { title: "Dishwasher", slug: "dishwasher" },
  { title: "Line Cook", slug: "line-cook" },
  { title: "Prep Cook", slug: "prep-cook" },
  { title: "Restaurant Manager", slug: "restaurant-manager" },
  { title: "Barista", slug: "barista" },
  { title: "Baker", slug: "baker" },
  { title: "Pastry Chef", slug: "pastry-chef" },
  { title: "Catering Manager", slug: "catering-manager" },
  { title: "Hotel Front Desk Clerk", slug: "hotel-front-desk-clerk" },
  { title: "Hotel Manager", slug: "hotel-manager" },
  { title: "Housekeeper", slug: "housekeeper" },
  { title: "Concierge", slug: "concierge" },

  // Healthcare (additional)
  { title: "Nursing Assistant", slug: "nursing-assistant" },
  { title: "Home Health Aide", slug: "home-health-aide" },
  { title: "Licensed Practical Nurse", slug: "licensed-practical-nurse" },
  { title: "Nurse Practitioner", slug: "nurse-practitioner" },
  { title: "Physician Assistant", slug: "physician-assistant" },
  { title: "Surgeon", slug: "surgeon" },
  { title: "Anesthesiologist", slug: "anesthesiologist" },
  { title: "Dermatologist", slug: "dermatologist" },
  { title: "Psychiatrist", slug: "psychiatrist" },
  { title: "Cardiologist", slug: "cardiologist" },
  { title: "Pediatrician", slug: "pediatrician" },
  { title: "Emergency Room Nurse", slug: "emergency-room-nurse" },
  { title: "Surgical Technologist", slug: "surgical-technologist" },
  { title: "Phlebotomist", slug: "phlebotomist" },
  { title: "Medical Records Technician", slug: "medical-records-technician" },
  { title: "Health Information Technician", slug: "health-information-technician" },
  { title: "Medical Billing Specialist", slug: "medical-billing-specialist" },
  { title: "Medical Coder", slug: "medical-coder" },
  { title: "Respiratory Therapist", slug: "respiratory-therapist" },
  { title: "MRI Technologist", slug: "mri-technologist" },
  { title: "Ultrasound Technician", slug: "ultrasound-technician" },
  { title: "Physical Therapy Assistant", slug: "physical-therapy-assistant" },
  { title: "Optician", slug: "optician" },
  { title: "Massage Therapist", slug: "massage-therapist" },
  { title: "Veterinary Technician", slug: "veterinary-technician" },
  { title: "Veterinary Assistant", slug: "veterinary-assistant" },

  // Office & Administrative
  { title: "Office Manager", slug: "office-manager" },
  { title: "Data Entry Clerk", slug: "data-entry-clerk" },
  { title: "File Clerk", slug: "file-clerk" },
  { title: "Secretary", slug: "secretary" },
  { title: "Legal Secretary", slug: "legal-secretary" },
  { title: "Medical Secretary", slug: "medical-secretary" },
  { title: "Office Clerk", slug: "office-clerk" },
  { title: "Billing Clerk", slug: "billing-clerk" },
  { title: "Payroll Clerk", slug: "payroll-clerk" },
  { title: "Accounts Payable Clerk", slug: "accounts-payable-clerk" },
  { title: "Accounts Receivable Clerk", slug: "accounts-receivable-clerk" },
  { title: "Bookkeeper", slug: "bookkeeper" },
  { title: "Mail Clerk", slug: "mail-clerk" },
  { title: "Shipping Clerk", slug: "shipping-clerk" },

  // Technology (additional)
  { title: "IT Support Specialist", slug: "it-support-specialist" },
  { title: "Help Desk Technician", slug: "help-desk-technician" },
  { title: "Network Administrator", slug: "network-administrator" },
  { title: "Systems Administrator", slug: "systems-administrator" },
  { title: "Database Administrator", slug: "database-administrator" },
  { title: "Cloud Engineer", slug: "cloud-engineer" },
  { title: "DevOps Engineer", slug: "devops-engineer" },
  { title: "Mobile App Developer", slug: "mobile-app-developer" },
  { title: "Frontend Developer", slug: "frontend-developer" },
  { title: "Backend Developer", slug: "backend-developer" },
  { title: "Full Stack Developer", slug: "full-stack-developer" },
  { title: "Machine Learning Engineer", slug: "machine-learning-engineer" },
  { title: "AI Engineer", slug: "ai-engineer" },
  { title: "Computer Hardware Engineer", slug: "computer-hardware-engineer" },
  { title: "IT Manager", slug: "it-manager" },
  { title: "Chief Technology Officer", slug: "chief-technology-officer" },
  { title: "Scrum Master", slug: "scrum-master" },
  { title: "Business Analyst", slug: "business-analyst" },
  { title: "Systems Analyst", slug: "systems-analyst" },
  { title: "Information Security Analyst", slug: "information-security-analyst" },
  { title: "Penetration Tester", slug: "penetration-tester" },
  { title: "Game Developer", slug: "game-developer" },
  { title: "Blockchain Developer", slug: "blockchain-developer" },

  // Finance & Banking (additional)
  { title: "Credit Analyst", slug: "credit-analyst" },
  { title: "Tax Preparer", slug: "tax-preparer" },
  { title: "Tax Accountant", slug: "tax-accountant" },
  { title: "Auditor", slug: "auditor" },
  { title: "Controller", slug: "controller" },
  { title: "Chief Financial Officer", slug: "chief-financial-officer" },
  { title: "Hedge Fund Manager", slug: "hedge-fund-manager" },
  { title: "Stockbroker", slug: "stockbroker" },
  { title: "Trader", slug: "trader" },
  { title: "Portfolio Manager", slug: "portfolio-manager" },
  { title: "Wealth Manager", slug: "wealth-manager" },
  { title: "Risk Analyst", slug: "risk-analyst" },
  { title: "Fraud Analyst", slug: "fraud-analyst" },
  { title: "Collections Specialist", slug: "collections-specialist" },

  // Manufacturing & Production
  { title: "Factory Worker", slug: "factory-worker" },
  { title: "Assembly Line Worker", slug: "assembly-line-worker" },
  { title: "Machine Operator", slug: "machine-operator" },
  { title: "CNC Machinist", slug: "cnc-machinist" },
  { title: "Welder", slug: "welder" },
  { title: "Quality Control Inspector", slug: "quality-control-inspector" },
  { title: "Production Supervisor", slug: "production-supervisor" },
  { title: "Plant Manager", slug: "plant-manager" },
  { title: "Manufacturing Engineer", slug: "manufacturing-engineer" },
  { title: "Industrial Engineer", slug: "industrial-engineer" },
  { title: "Process Engineer", slug: "process-engineer" },
  { title: "Packaging Operator", slug: "packaging-operator" },
  { title: "Forklift Operator", slug: "forklift-operator" },

  // Construction & Trades (additional)
  { title: "Carpenter", slug: "carpenter" },
  { title: "Painter", slug: "painter" },
  { title: "Roofer", slug: "roofer" },
  { title: "Concrete Worker", slug: "concrete-worker" },
  { title: "Bricklayer", slug: "bricklayer" },
  { title: "Tile Setter", slug: "tile-setter" },
  { title: "Flooring Installer", slug: "flooring-installer" },
  { title: "Drywall Installer", slug: "drywall-installer" },
  { title: "Glazier", slug: "glazier" },
  { title: "Ironworker", slug: "ironworker" },
  { title: "Crane Operator", slug: "crane-operator" },
  { title: "Heavy Equipment Operator", slug: "heavy-equipment-operator" },
  { title: "Surveyor", slug: "surveyor" },
  { title: "Building Inspector", slug: "building-inspector" },
  { title: "General Contractor", slug: "general-contractor" },
  { title: "Solar Panel Installer", slug: "solar-panel-installer" },
  { title: "Elevator Mechanic", slug: "elevator-mechanic" },
  { title: "Pipefitter", slug: "pipefitter" },
  { title: "Steamfitter", slug: "steamfitter" },
  { title: "Sheet Metal Worker", slug: "sheet-metal-worker" },
  { title: "Boilermaker", slug: "boilermaker" },

  // Transportation & Logistics (additional)
  { title: "Bus Driver", slug: "bus-driver" },
  { title: "Delivery Driver", slug: "delivery-driver" },
  { title: "Courier", slug: "courier" },
  { title: "Uber Driver", slug: "uber-driver" },
  { title: "Lyft Driver", slug: "lyft-driver" },
  { title: "Pilot", slug: "pilot" },
  { title: "Commercial Pilot", slug: "commercial-pilot" },
  { title: "Airline Pilot", slug: "airline-pilot" },
  { title: "Train Conductor", slug: "train-conductor" },
  { title: "Locomotive Engineer", slug: "locomotive-engineer" },
  { title: "Ship Captain", slug: "ship-captain" },
  { title: "Deckhand", slug: "deckhand" },
  { title: "Freight Handler", slug: "freight-handler" },
  { title: "Dispatcher", slug: "dispatcher" },
  { title: "Warehouse Manager", slug: "warehouse-manager" },
  { title: "Inventory Specialist", slug: "inventory-specialist" },
  { title: "Purchasing Agent", slug: "purchasing-agent" },

  // Education (additional)
  { title: "Elementary School Teacher", slug: "elementary-school-teacher" },
  { title: "High School Teacher", slug: "high-school-teacher" },
  { title: "Middle School Teacher", slug: "middle-school-teacher" },
  { title: "Special Education Teacher", slug: "special-education-teacher" },
  { title: "Preschool Teacher", slug: "preschool-teacher" },
  { title: "Teaching Assistant", slug: "teaching-assistant" },
  { title: "School Counselor", slug: "school-counselor" },
  { title: "School Principal", slug: "school-principal" },
  { title: "College Professor", slug: "college-professor" },
  { title: "Tutor", slug: "tutor" },
  { title: "ESL Teacher", slug: "esl-teacher" },
  { title: "Librarian", slug: "librarian" },
  { title: "Instructional Designer", slug: "instructional-designer" },
  { title: "Corporate Trainer", slug: "corporate-trainer" },
  { title: "Education Administrator", slug: "education-administrator" },

  // Creative & Media (additional)
  { title: "Film Director", slug: "film-director" },
  { title: "Cinematographer", slug: "cinematographer" },
  { title: "Film Editor", slug: "film-editor" },
  { title: "Sound Engineer", slug: "sound-engineer" },
  { title: "Animator", slug: "animator" },
  { title: "3D Artist", slug: "3d-artist" },
  { title: "Motion Graphics Designer", slug: "motion-graphics-designer" },
  { title: "Art Director", slug: "art-director" },
  { title: "Creative Director", slug: "creative-director" },
  { title: "Illustrator", slug: "illustrator" },
  { title: "Fine Artist", slug: "fine-artist" },
  { title: "Musician", slug: "musician" },
  { title: "Singer", slug: "singer" },
  { title: "Voice Actor", slug: "voice-actor" },
  { title: "Actor", slug: "actor" },
  { title: "Radio Host", slug: "radio-host" },
  { title: "Podcast Producer", slug: "podcast-producer" },
  { title: "Broadcast Journalist", slug: "broadcast-journalist" },
  { title: "News Anchor", slug: "news-anchor" },

  // Marketing & Communications (additional)
  { title: "Public Relations Specialist", slug: "public-relations-specialist" },
  { title: "Communications Manager", slug: "communications-manager" },
  { title: "Brand Manager", slug: "brand-manager" },
  { title: "SEO Specialist", slug: "seo-specialist" },
  { title: "PPC Specialist", slug: "ppc-specialist" },
  { title: "Digital Marketing Manager", slug: "digital-marketing-manager" },
  { title: "Email Marketing Specialist", slug: "email-marketing-specialist" },
  { title: "Advertising Manager", slug: "advertising-manager" },
  { title: "Media Buyer", slug: "media-buyer" },
  { title: "Media Planner", slug: "media-planner" },
  { title: "Content Strategist", slug: "content-strategist" },

  // Legal (additional)
  { title: "Legal Assistant", slug: "legal-assistant" },
  { title: "Court Reporter", slug: "court-reporter" },
  { title: "Judge", slug: "judge" },
  { title: "Mediator", slug: "mediator" },
  { title: "Patent Attorney", slug: "patent-attorney" },
  { title: "Corporate Lawyer", slug: "corporate-lawyer" },
  { title: "Criminal Defense Attorney", slug: "criminal-defense-attorney" },
  { title: "Immigration Lawyer", slug: "immigration-lawyer" },
  { title: "Contract Specialist", slug: "contract-specialist" },

  // Science & Research
  { title: "Research Scientist", slug: "research-scientist" },
  { title: "Lab Technician", slug: "lab-technician" },
  { title: "Chemist", slug: "chemist" },
  { title: "Biologist", slug: "biologist" },
  { title: "Microbiologist", slug: "microbiologist" },
  { title: "Environmental Scientist", slug: "environmental-scientist" },
  { title: "Geologist", slug: "geologist" },
  { title: "Physicist", slug: "physicist" },
  { title: "Astronomer", slug: "astronomer" },
  { title: "Statistician", slug: "statistician" },
  { title: "Epidemiologist", slug: "epidemiologist" },
  { title: "Food Scientist", slug: "food-scientist" },
  { title: "Agricultural Scientist", slug: "agricultural-scientist" },

  // Human Services
  { title: "Childcare Worker", slug: "childcare-worker" },
  { title: "Nanny", slug: "nanny" },
  { title: "Counselor", slug: "counselor" },
  { title: "Marriage and Family Therapist", slug: "marriage-family-therapist" },
  { title: "Substance Abuse Counselor", slug: "substance-abuse-counselor" },
  { title: "Mental Health Counselor", slug: "mental-health-counselor" },
  { title: "Case Manager", slug: "case-manager" },
  { title: "Community Health Worker", slug: "community-health-worker" },
  { title: "Rehabilitation Counselor", slug: "rehabilitation-counselor" },
  { title: "Clergy", slug: "clergy" },
  { title: "Funeral Director", slug: "funeral-director" },

  // Protective Services
  { title: "Police Officer", slug: "police-officer" },
  { title: "Detective", slug: "detective" },
  { title: "Firefighter", slug: "firefighter" },
  { title: "Paramedic", slug: "paramedic" },
  { title: "EMT", slug: "emt" },
  { title: "Correctional Officer", slug: "correctional-officer" },
  { title: "Private Investigator", slug: "private-investigator" },
  { title: "TSA Agent", slug: "tsa-agent" },
  { title: "Border Patrol Agent", slug: "border-patrol-agent" },
  { title: "Lifeguard", slug: "lifeguard" },

  // Personal Care & Services
  { title: "Hairdresser", slug: "hairdresser" },
  { title: "Barber", slug: "barber" },
  { title: "Makeup Artist", slug: "makeup-artist" },
  { title: "Nail Technician", slug: "nail-technician" },
  { title: "Esthetician", slug: "esthetician" },
  { title: "Personal Stylist", slug: "personal-stylist" },
  { title: "Pet Groomer", slug: "pet-groomer" },
  { title: "Dog Walker", slug: "dog-walker" },
  { title: "Personal Chef", slug: "personal-chef" },
  { title: "House Cleaner", slug: "house-cleaner" },
  { title: "Janitor", slug: "janitor" },
  { title: "Landscaper", slug: "landscaper" },
  { title: "Groundskeeper", slug: "groundskeeper" },
  { title: "Pest Control Technician", slug: "pest-control-technician" },

  // Sports & Recreation
  { title: "Fitness Instructor", slug: "fitness-instructor" },
  { title: "Yoga Instructor", slug: "yoga-instructor" },
  { title: "Sports Coach", slug: "sports-coach" },
  { title: "Athletic Trainer", slug: "athletic-trainer" },
  { title: "Recreation Worker", slug: "recreation-worker" },
  { title: "Tour Guide", slug: "tour-guide" },
  { title: "Travel Agent", slug: "travel-agent" },
  { title: "Casino Dealer", slug: "casino-dealer" },
  { title: "Gaming Manager", slug: "gaming-manager" },

  // Agriculture & Environment
  { title: "Farmer", slug: "farmer" },
  { title: "Agricultural Worker", slug: "agricultural-worker" },
  { title: "Rancher", slug: "rancher" },
  { title: "Fisherman", slug: "fisherman" },
  { title: "Logger", slug: "logger" },
  { title: "Arborist", slug: "arborist" },
  { title: "Environmental Engineer", slug: "environmental-engineer" },
  { title: "Conservation Scientist", slug: "conservation-scientist" },
  { title: "Park Ranger", slug: "park-ranger" },
  { title: "Zookeeper", slug: "zookeeper" },

  // Executive & Management
  { title: "Chief Executive Officer", slug: "chief-executive-officer" },
  { title: "Chief Operating Officer", slug: "chief-operating-officer" },
  { title: "Chief Marketing Officer", slug: "chief-marketing-officer" },
  { title: "General Manager", slug: "general-manager" },
  { title: "Program Manager", slug: "program-manager" },
  { title: "Management Consultant", slug: "management-consultant" },
  { title: "Facilities Manager", slug: "facilities-manager" },
  { title: "Property Manager", slug: "property-manager" },
  { title: "Leasing Agent", slug: "leasing-agent" },
]

// Verify count
console.log(`Total job candidates: ${jobCandidates.length}`)
